### ISSUE TITLE
Video List Empty (Hi Anime Extension)

### ISSUE THREAD

**Issue by hungry-for-code** [aniyomiorg/aniyomi-extensions#3230] opened 2024-05-13 02:28 UTC
### Source information

HiAnime 14.43

### Source language

English

### Steps to reproduce

1. The anime is currently airing. 
2. Whenever I open the new episodes(in app), it says video list empty. 
3. In the website the new episode is there.
4. The old episodes are playing fine. 

### Expected behavior

Video should play cause the episode has been uploaded in the website . 

### Actual behavior

Video doesn't play and says bideo list empty. 

### Aniyomi version

App version: 0.15.3.0 

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-05-13 05:30
Duplicate of #3061

**Closed by Secozzi** 2024-05-13 05:30 UTC
Labels: Bug
