### ISSUE TITLE
HiAnime Video List Empty

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi-extensions#3113] opened 2024-03-28 21:26 UTC
### Source information

Hi anime 14.42

### Source language

English 

### Steps to reproduce

1. Open a currently airing anime in HiAnime.
2. Try to play the latest episode.

### Expected behavior

The episode should play .

### Actual behavior

An error saying "Video List Empty" shows up.
![Screenshot_20240329-024903_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/107224555/93061260-fdc6-4b6e-8d06-ac53e89e0f42)
Logs: 
[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi-extensions/files/14795740/aniyomi_crash_logs.txt)

### Aniyomi version

Aniyomi Preview r7513

### Android version

Android 14 

### Other details

This error only happens on the latest episode of an anime and not the previously aired ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-28 21:29
Duplicate of #3061

**Closed by Secozzi** 2024-03-28 21:29 UTC
Labels: Bug

**Comment by YouSummoner** [comment] 2024-03-28 21:32
This is not a Duplicate, it's for another bug.... Please Reopen this issue......

**Comment by fakebhai** [comment] 2024-03-28 21:34
> This is not a Duplicate, it's for another bug.... Please Reopen this issue......

because there's no sub or dub available for that episode (raw is available)
