### ISSUE TITLE
Kickassanime

### ISSUE THREAD

**Issue by Fidelo8** [aniyomiorg/aniyomi-extensions#2702] opened 2024-01-07 04:58 UTC
### Source information

Kickass anime v. 13.36

### Source language

English 

### Steps to reproduce

Playing any episode fail to fecha episode 

### Expected behavior

Play video 

### Actual behavior

Doesn't play any episode

### Aniyomi version

App version: 0.14.6-6691 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-01-07 11:03
Duplicate of #2259

**Closed by Secozzi** 2024-01-07 11:03 UTC
Labels: Bug
