### ISSUE TITLE
Anime balkom 13.12 corrupted photo cover

### ISSUE THREAD

**Issue by AbdulrahmanIII** [aniyomiorg/aniyomi-extensions#2091] opened 2023-08-27 11:06 UTC
### Source information

انمي بالكوم 13.12

### Source language

Arabic, العربية

### Steps to reproduce

1.go to anime sources
2. Choose انمي بالكوم 

### Expected behavior

See the cover photo of the anime

### Actual behavior

Cover photos links  appear to be broken and are not shown

### Aniyomi version

App version: 0.14.5-6424 standard and the beta 

### Android version

Android 12

### Other details

![Screenshot_20230827-135333_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/108073746/b5f2c490-8a6f-4a66-9f05-fd9e213ef9f7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-08-27 11:07
Duplicate of #2084

**Closed by Secozzi** 2023-08-27 11:07 UTC
Labels: Bug
