### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by SaurabhKaperwan** [aniyomiorg/aniyomi-extensions#2609] opened 2023-12-05 04:09 UTC
### Source name

Vegamovies and Dotmovies

### Source link

https://dotmovies.gay/

### Source language

English ,Hindi

### Other details

https://m.vegamovies.boo/

https://dotmovies.gay/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment] 2023-12-05 07:03
Duplicate of #2180. Also, you're supposed to request only a single(one(01)) extension per issue.

**Closed by Claudemirovsky** 2023-12-05 07:03 UTC
Labels: Source request

**Comment by fakebhai** [comment] 2023-12-05 08:56
> Duplicate of #2180. Also, you're supposed to request only a single(one(01)) extension per issue.

both sites are looking kinda same, maybe it could be used as multi?
seems we can even use domain change but both of them have different content
dot movies seems to be more on Indian Content.
