### ISSUE TITLE
Animeunity not working

### ISSUE THREAD

**Issue by evaltin** [aniyomiorg/aniyomi-extensions#3279] opened 2024-05-30 08:31 UTC
### Source information

Animeunity

### Source language

Italian

### Steps to reproduce

Failed to fetch videos for anything

### Expected behavior

Should work

### Actual behavior

Doesn't 

### Aniyomi version

App version: 0.15.3.0 (standard, c91fb86, 123, 2024-05-10T08:46Z) Android version: 10 (SDK 29; build QP1A.190711.020 release-keys) Android build ID: QP1A.190711.020 release-keys Device brand: vivo Device manufacturer: vivo Device name: PD1914 (PD1914) Device model: V1914A WebView: Android System WebView 124.0.6367.179 MPV version: c6ccabe Libplacebo version: v7.349.0 FFmpeg version: n6.1.1

### Android version

Origin Os 1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-05-30 08:32
Duplicate of #3269

**Closed by Secozzi** 2024-05-30 08:32 UTC
Labels: Bug
