### ISSUE TITLE
Web view not working properly

### ISSUE THREAD

**Issue by zerakori** [aniyomiorg/aniyomi-extensions#2788] opened 2024-01-19 15:16 UTC
### Source information

Aniwatch

### Source language

English

### Steps to reproduce

First open an anime through aniwatch,
Then open web view of that anime 
Any approach to watch the episode on web view will reflect to home page

### Expected behavior

It should let me watch the episode on the web view

### Actual behavior

But it redirects to another page

### Aniyomi version

r7473

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-01-26 10:24
Duplicate of #2690

**Closed by Secozzi** 2024-01-26 10:24 UTC
Labels: Bug
