### ISSUE TITLE
Streamingcommunity extension doesn't work

### ISSUE THREAD

**Issue by ed0fl3da** [aniyomiorg/aniyomi-extensions#3108] opened 2024-03-28 12:07 UTC
### Source information

Streamingcommunity 

### Source language

Italian

### Steps to reproduce

Download extension
Open extension
Search movie or TV series
Play

### Expected behavior

Movie or TV series play

### Actual behavior

Doesn't play

### Aniyomi version

Latest

### Android version

Latest

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-28 12:09
Duplicate of #2477

**Closed by Secozzi** 2024-03-28 12:09 UTC
Labels: Bug
