### ISSUE TITLE
anime4up new domain

### ISSUE THREAD

**Issue by 3bakri** [aniyomiorg/aniyomi-extensions#2307] opened 2023-10-02 19:21 UTC
### Source information

anime4up 13.50

### Source language

Arabic 

### Source new URL

https://anime4up.site/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-10-02 19:31
Duplicate of #2291
Next time, please just edit your existing issue, or leave a comment if it wasn't opened by you, instead of blanking out all the information and opening a new one if there's new information

**Closed by Secozzi** 2023-10-02 19:31 UTC
Labels: Bug, Domain changed

**Comment by 3bakri** [comment] 2023-10-03 16:06
I updated the information but really they urged the url
