### ISSUE TITLE
Aniwave extension not working 

### ISSUE THREAD

**Issue by deneshwarbhandarkar** [aniyomiorg/aniyomi-extensions#3142] opened 2024-04-06 15:08 UTC
### Source information

Aniwave 14.66

### Source language

English 

### Steps to reproduce

Open Aniwave extension 
Search for any anime
Try to watch video

### Expected behavior

Videos should play

### Actual behavior

JsonDecodingException: Unexpected JSON token at offset 23: Expected string literal but 'null' literal was found at path: $.result

Use 'coercelnputValues = true' in 'Json {)' builder to coerce nulls to default values.

JSON input: {"status":403,"result":null,"message":"Request is invalid.","messages":["Request is invalid."]}
![Screenshot_2024-04-06-20-36-44-44_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/97867120/4a02acca-e8ed-461c-80b1-eab81afe111c)

### Aniyomi version

0.15.2.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-04-06 15:13
Duplicate of #3109

**Closed by Secozzi** 2024-04-06 15:13 UTC
Labels: Bug

**Comment by deneshwarbhandarkar** [comment] 2024-04-06 15:19
Issue is not resolved yet
Many are facing this issue
