### ISSUE TITLE
Arabic source AnimeSanka

### ISSUE THREAD

**Issue by qwkli** [aniyomiorg/aniyomi-extensions#2598] opened 2023-12-02 11:34 UTC
### Source name

AnimeSanka انمي سانكا

### Source link

https://www.anime-sanka.com/

### Source language

Arabic

### Other details

I saw duplicates but it's not available as a source to use. Please add this source and thanks!
![Screenshot_20231202_143258_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/152696210/887cd73f-41bc-4ed7-b757-0e651494aac2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-12-02 11:35
Duplicate of #1087

**Closed by Secozzi** 2023-12-02 11:35 UTC
Labels: Source request
