### ISSUE TITLE
[Aniwatch] new episodes and videostream server not working

### ISSUE THREAD

**Issue by Justpp1234** [aniyomiorg/aniyomi-extensions#1942] opened 2023-07-22 12:12 UTC
### Source information

Aniwatch

### Source language

English

### Steps to reproduce

Solve

### Expected behavior

Play video

### Actual behavior

Dont play video
Infinite loading
![Screenshot_20230722-174157](https://github.com/aniyomiorg/aniyomi-extensions/assets/124712825/f4dd2489-d2b8-4bbf-bd80-3de64788ec7a)

### Aniyomi version

Preview 6151

### Android version

Andriod 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-23 09:45
Duplicate of #1931

**Closed by Secozzi** 2023-07-23 09:45 UTC
Labels: Bug
