### ISSUE TITLE
Problem are coming in library new episodes are not showing in library

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi-extensions#2995] opened 2024-03-04 09:10 UTC
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/9f1c264e-2f20-4e31-998d-592cb4b8213c)

### Expected behavior

Slide down in library option are episodes are not showing

### Actual behavior

Please 
![Screenshot_2024-03-03-19-27-53-51_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/8be95a59-4457-40ed-871e-bd409406fb61)

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Other details

Please take action 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-04 09:11
Duplicate of #2986

**Closed by Secozzi** 2024-03-04 09:11 UTC
Labels: Bug
