### ISSUE TITLE
Kuramanime  Video List is empty

### ISSUE THREAD

**Issue by Shiin-79** [aniyomiorg/aniyomi-extensions#3286] opened 2024-06-01 08:03 UTC
### Source information

Kuramanime 

### Source language

Indonesia

### Steps to reproduce

When you want to watch you can't play the video, there is a statement Video List is empty.

and base url change https://kuramanime.boo/

### Expected behavior

..

### Actual behavior

...

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-06-01 08:05
Duplicate of #2662

**Closed by Secozzi** 2024-06-01 08:05 UTC
Labels: Bug
