### ISSUE TITLE
Failed to extract video. Please read before closing.

### ISSUE THREAD

**Issue by MegaMinus** [aniyomiorg/aniyomi-extensions#2685] opened 2023-12-30 16:45 UTC
### Source information

AniWatch 13.36 (English)

### Source language

English

### Steps to reproduce

Play any episode of any anime.

### Expected behavior

It should let me watch it 

### Actual behavior

It just goes back and says Failed to extract video.

### Aniyomi version

Preview r6691

### Android version

Android 13

### Other details

It happens pretty randomly. But when this happens it won't work for a long time. It is very annoying and last time it got closed even though it was not fixed. This happens with the extension Kaido as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-12-30 16:46
Duplicate of #2568

**Closed by Secozzi** 2023-12-30 16:46 UTC
Labels: Bug
