### ISSUE TITLE
Extensions issues 

### ISSUE THREAD

**Issue by Yukiyuki99** [aniyomiorg/aniyomi-extensions#2982] opened 2024-03-01 22:09 UTC
### Source information

SFlix English 14.24 and FMovies 14.19

### Source language

English

### Steps to reproduce

I try to open the video and it shows me "video list Empty" on SFlix extension 
![Screenshot_20240301_232519_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/161888577/75f6ee45-befb-4838-90b4-d5a351b67518)
And it give errors on FMovies extension 
![Screenshot_20240301_225230_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/161888577/bbf64437-4c80-47aa-bd9b-dbc6ff3b235d)
![Screenshot_20240301_225210_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/161888577/24ca73f7-ed28-4042-b31f-10ea612df34b)

### Expected behavior

It should open when I clicked on the video 

### Actual behavior

When I try to open an episode or an movie it show " Video Empty list" and nothing work the video don't open on SFlix
![Screenshot_20240301_232519_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/161888577/76e7b344-99d2-4032-a6b8-1b55ab7466ca)
and on FMovies it shows this writing when I try to open an video 
![Screenshot_20240301_225210_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/161888577/da028983-8b14-4d6c-b1a7-eb2b4afda198)
![Screenshot_20240301_225230_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/161888577/2aeb69cc-d635-4400-8684-8c29da36685b)

### Aniyomi version

0.15.2.4

### Android version

13

### Other details

I was happy when I saw the extensions to watch movies and TV shows I hope you can fix the extensions please I don't know what Is wrong I tried to uninstall and install the app multiple times it still don't work I don't know what to do 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-01 22:11
Duplicate of #2935 and #2975 , next time please only open one issue per source

**Closed by Secozzi** 2024-03-01 22:11 UTC
Labels: Bug
