### ISSUE TITLE
Dopebox Video list empty 

### ISSUE THREAD

**Issue by stevenwhat68** [aniyomiorg/aniyomi-extensions#2952] opened 2024-02-19 09:29 UTC
### Source information

Dope box 14.47

### Source language

English 

### Steps to reproduce

1. I open any series or movie
2. I click an episode or the movie
3. Then it will back out to episode list
4. Then it will show a Text on the bottom With the writing of video list empty 

### Expected behavior

Its should show me the episode and movies

### Actual behavior

But all it do is force close back to the episode list, and show a text that the video list is empty even though there is clearly an episode

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Other details

That's all i find, but it is also the same with other app like sflix

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-02-19 09:36
Duplicate of #2935

**Closed by Secozzi** 2024-02-19 09:36 UTC
Labels: Bug
