### ISSUE TITLE
All my installed extension is bugged

### ISSUE THREAD

**Issue by Shinmentakezo0** [aniyomiorg/aniyomi-extensions#1973] opened 2023-07-29 02:18 UTC
### Source information

Fmovies,9anime, animekaizoku,aniwatch.to

### Source language

English 

### Steps to reproduce

1. All my installed extension got this bug
2. Extension who I didn't installed is working perfectly fine
3. Missing field exception bug

### Expected behavior

![Screenshot_2023-07-29-10-00-07-16_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/140866459/84fb5ce9-1ff3-4261-96b8-43b125fa97ac)
So I was about to download flash then this bug message comes in idk why I haven't done anything to it so I thought of reinstalling it 

### Actual behavior

Turns out the bug is still on it that's why I had to give this so you guys could fix this ASAP

### Aniyomi version

r6453

### Android version

Android 11

### Other details

I tried to clear cookies change server clear database clear WebView , and still the bug is on there

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-29 08:23
Animekaizoku has permanently shut down, aniwatch is a duplicate of #1931 , fmovies and 9anime is a duplicate of #1970 . Next time open one issue per extension, since they don't all have the same exact issue.

**Closed by Secozzi** 2023-07-29 08:23 UTC
Labels: Bug

**Comment by spicyroe** [comment] 2023-07-29 08:49
@Secozzi can i ask exactly is the issue and what it means in 9anime and possible fixes. Thank you!

**Comment by Shinmentakezo0** [comment] 2023-07-29 09:10
So basically this only happened this day idk why my other friend and
siblings also have this bug and I think it's global , the issue is each
time we download or online stream from all the sources we installed before
this day is having this issue

 "MissingFieldException: Field 'url' is required for type with serial name
'eu.kanade.tachiyomi.animeextension.en.nineanime.NineAnime.VrfResponse',
but it was missing at path: $ "

So I don't know how this happened and also I tried other extension which I
haven't installed once and they are perfectly working. I hope you guys can
fix this ASAP

**Comment by Secozzi** [comment] 2023-07-29 09:50
We were using a helper server to encrypt/decrypt message required for the extension to work because of the difficulties involved in doing it all inside the extension. Due to some problem with said server, it had to be taken down for the moment which causes the error shown. There isn't anything that can be done on the user's part, so just wait for an extension update.

**Comment by Shinmentakezo0** [comment] 2023-07-29 10:23
Ok, I will wait. How many days can an extension get update?

**Comment by Secozzi** [comment] 2023-07-29 21:29
> Ok, I will wait. How many days can an extension get update?

No ETA
