### ISSUE TITLE
Kayoanime Isn't working

### ISSUE THREAD

**Issue by Imon24** [aniyomiorg/aniyomi-extensions#1879] opened 2023-07-09 06:36 UTC
### Source information and language

Kayoanime 13.6

### Steps to reproduce

Anime posters are showing. But episode aren’t loading. I even logged in with Google

### Expected behavior

Anime episcopes link should appear

### Actual behavior

No episode links are appearing

### Aniyomi version

Beta r6151

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-09 08:38
Duplicate of #1855

**Closed by Secozzi** 2023-07-09 08:38 UTC
Labels: Bug
