### ISSUE TITLE
(انمي بالكوم)cover photos for anime stopped showing up

### ISSUE THREAD

**Issue by zrql** [aniyomiorg/aniyomi-extensions#2089] opened 2023-08-27 06:50 UTC
### Source information

انمي بالكوم 13.12

### Source language

arabic

### Steps to reproduce

the cover photos for anime stopped showing up

### Expected behavior

cover photos for anime should appear

### Actual behavior

cover photos for anime stopped showing up

### Aniyomi version

preview r6151

### Android version

emui 12

### Other details

after the update, cover photos for anime stopped showing up 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-08-27 08:14
Duplicate of #2084

**Closed by Secozzi** 2023-08-27 08:14 UTC
Labels: Bug
