### ISSUE TITLE
Fmovies and 9anime still not working after their respective updates

### ISSUE THREAD

**Issue by Fromsoftie** [aniyomiorg/aniyomi-extensions#2048] opened 2023-08-15 08:35 UTC
### Source information

"Fmovies 13.5" and "9anime 13.47"

### Source language

English

### Steps to reproduce

1. Open app
2. Click on episode
3. Cant stream the episode

### Expected behavior

Streaming content  

### Actual behavior

Error

### Aniyomi version

App version: 0.12.3.10

### Android version

Galaxy S22 Ultra

### Other details

Not sure if it's allowed to post about two errors in 1 post, but didin't want to spam.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-08-15 14:20
Duplicate of #2004 and #1970, also next time please don't make a single issue for multiple extensions. Makes it easier to manage if it's one issue per source.

**Closed by Secozzi** 2023-08-15 14:20 UTC
Labels: Bug
