### ISSUE TITLE
No episode found gogoanime domain 

### ISSUE THREAD

**Issue by akumarsmapp** [aniyomiorg/aniyomi-extensions#2998] opened 2024-03-04 11:59 UTC
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

![Screenshot_2024-03-04-17-26-15-24_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/136121093/aeba93c5-8257-458d-9c02-9b5a3b9b988e)

### Expected behavior

Message are coming 

No episode are found 

### Actual behavior

Refresh the page episodes are not coming

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Other details

Please solve this problem 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-04 12:00
Duplicate of #2986

**Comment by akumarsmapp** [comment] 2024-03-04 12:01
Episode are not coming

**Closed by Secozzi** 2024-03-04 12:00 UTC
Labels: Bug

**Comment by akumarsmapp** [comment] 2024-03-04 12:03
What is your problem

Why are Remove this problem

**Comment by Secozzi** [comment] 2024-03-04 12:04
Because its a duplicate of the issue i mentioned

**Comment by akumarsmapp** [comment] 2024-03-04 12:07
Ok but episodes are not coming to but I can do I am delete my app and download again but same problem are coming no episode are found this message are coming I am refresh my gogoanime library but episode are not coming other I am good other I am go to the browser and open GoGoAnime exception and check another anime name episode are not download and not found is coming

**Comment by akumarsmapp** [comment] 2024-03-04 12:09
If you have a solution give me please

**Comment by Secozzi** [comment] 2024-03-04 12:10
The extension is broken, hence the issue i mentioned earlier. Wait for an extension update.

**Comment by akumarsmapp** [comment] 2024-03-04 12:14
Ok if update are coming please tell me
Because I was go browser open and gogoanime domain

And I am click any anime option
They show message are coming no episode found

**Comment by akumarsmapp** [comment] 2024-03-04 12:15
Also I have another problem after the update my app

Manga extension are not working please solve this also my problem

**Comment by Secozzi** [comment] 2024-03-04 12:16
Don't comment with unrelated issues. If you have a separate problem, make a separate bug report.

**Comment by akumarsmapp** [comment] 2024-03-04 12:20
> Don't comment with unrelated issues. If you have a separate problem, make a separate bug report.

I am using older version aniyomi app

If I am update my app Manga extensions are not working
