### ISSUE TITLE
[Source Request] <Nekonime>

### ISSUE THREAD

**Issue by willyreza** [aniyomiorg/aniyomi-extensions#743] opened 2022-08-08 13:55 UTC
## Source website
- Name: Nekonime
- Link: https://nekonime.net/
- Language(s): Indonesian

## Other details

Streaming Anime Sub Indonesia

**Comment by Secozzi** [comment] 2023-06-16 19:46
Duplicate of #154

**Closed by Secozzi** 2023-06-16 19:46 UTC
