### ISSUE TITLE
[Source Request] <Anime iat>

### ISSUE THREAD

**Issue by Akashi123-deep** [aniyomiorg/aniyomi-extensions#471] opened 2022-04-09 01:38 UTC
New source for anime
Name : anime iat
Link site : https://www.animeiat.tv/
Language : Arabic 
![Screenshot_20220409-012716_Chrome](https://user-images.githubusercontent.com/102795903/162551534-0d7165bf-0ace-4ea8-a17f-f847d36adfd5.jpg)

**Comment by Secozzi** [comment] 2023-06-16 14:55
Duplicate of #344

**Closed by Secozzi** 2023-06-16 14:55 UTC
