### ISSUE TITLE
AnimelatinoHD don't work

### ISSUE THREAD

**Issue by ButeryMetal** [aniyomiorg/aniyomi-extensions#3074] opened 2024-03-21 16:53 UTC
### Source information

AnimelatinoHD

### Source language

Spanish

### Steps to reproduce

1. Install the source
2. Open the source

### Expected behavior

The source should work

### Actual behavior

Source don't work
![20240321_105126](https://github.com/aniyomiorg/aniyomi-extensions/assets/156118288/14be637d-bd84-4b18-a446-56af38facbaf)

### Aniyomi version

0.15.2.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-21 16:55
Duplicate of #3014

**Closed by Secozzi** 2024-03-21 16:55 UTC
Labels: Bug
