### ISSUE TITLE
Aniwatch extension url change detection 

### ISSUE THREAD

**Issue by Blank5635** [aniyomiorg/aniyomi-extensions#2969] opened 2024-02-24 20:35 UTC
### Source information

Aniwatch

### Source language

English

### Source new URL

Https://aniwatchtv.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-02-24 20:36
Duplicate of #2690

**Closed by Secozzi** 2024-02-24 20:36 UTC
Labels: Bug, Domain changed
