### ISSUE TITLE
Video List Empty Issue

### ISSUE THREAD

**Issue by derellabfs** [aniyomiorg/aniyomi-extensions#2923] opened 2024-02-13 14:35 UTC
### Source information

Sflix

### Source language

English 

### Steps to reproduce

1. Click on any drama/movie in Sflix extension
2. The overview page is open
3. Click on any episode available on the episodes list
4. The "video list is empty" notice pops up

### Expected behavior

The episode should be playing 

### Actual behavior

The episode not played and a "video list is empty" notice shows up instead

### Aniyomi version

v0.15.2.4

### Android version

Android 11

### Other details

I already checked the website and the episodes are still available and the website is working just fine 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-02-13 14:36
Duplicate of #2920

**Closed by Secozzi** 2024-02-13 14:36 UTC
Labels: Bug
