### ISSUE TITLE
[Source Request] <Anichin>

### ISSUE THREAD

**Issue by willyreza** [aniyomiorg/aniyomi-extensions#723] opened 2022-08-04 13:27 UTC
## Source website
- Name: Anichin
- Link: https://anichin.my.id/
- Language(s): Indonesian

## Other details

Streaming Donghua (Anime China) Sub Indonesia

**Comment by Samfun75** [comment] 2023-06-16 16:50
Duplicate of #122

**Closed by Samfun75** 2023-06-16 16:50 UTC
