### ISSUE TITLE
Multimovies extension error

### ISSUE THREAD

**Issue by Checkmate-nOvA** [aniyomiorg/aniyomi-extensions#3226] opened 2024-05-09 23:42 UTC
### Source information

Multimovies 14.18

### Source language

English

### Steps to reproduce

1.Open multimovies
2.try to watch a episode
3.shows Null Exception error: null
![Screenshot_20240510-044013](https://github.com/aniyomiorg/aniyomi-extensions/assets/169409558/8348b30a-14ac-45d4-9c15-256fe0855813)

### Expected behavior

It should show the number of episodes present in the series.

### Actual behavior

It showed Null exception error: null
![Screenshot_20240510-043956](https://github.com/aniyomiorg/aniyomi-extensions/assets/169409558/2e649d33-a49f-45e1-bb8e-3512c8343327)

### Aniyomi version

App version: 0.15.2.4-7519 (standard, cffb5a8ae, 122, 2024-04-12T07:34Z) Android version: 11 (SDK 30; build KF8-H696ABFAlAm-R-GL-230324V1663) Android build ID: KF8-H696ABFAlAm-R-GL-230324V1663 Device brand: TECNO Device manufacturer: TECNO MOBILE LIMITED Device name: TECNO-KF8 (KF8-GL) Device model: TECNO KF8 WebView: Android System WebView 124.0.6367.123 MPV version: c6ccabe Libplacebo version: v7.349.0 FFmpeg version: n6.1.1

### Android version

Android 11

### Other details

It firstly shows that source provides zero episodes than it shows that null exception error : null

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Checkmate-nOvA** [comment] 2024-05-09 23:43
Plz fix it if you can...

**Comment by fakebhai** [comment] 2024-05-10 10:38
relevant/duplicate of #2785 #3067

**Closed** 2024-06-14 08:13 UTC
Labels: Bug
