### ISSUE TITLE
dopebox and sflix not working

### ISSUE THREAD

**Issue by CntrlX** [aniyomiorg/aniyomi-extensions#1966] opened 2023-07-28 15:17 UTC
### Source information

dopebox 13.19, sflix 13.18

### Source language

English

### Steps to reproduce

play any video in the extension

### Expected behavior

video should start

### Actual behavior

says couldn't find video links

### Aniyomi version

0.12.3.10

### Android version

12

### Other details

i have checked the direct link an example link of a file is https://dokicloud.one/ajax/embed-4/getSources?id=FJcBCfCv5c3D here you can see that the sources field is blank or null  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-28 15:57
Duplicate of #1943

**Closed by Secozzi** 2023-07-28 15:57 UTC
Labels: Bug
