### ISSUE TITLE
YOMIROLL Error 

### ISSUE THREAD

**Issue by RuDru-OP** [aniyomiorg/aniyomi-extensions#1851] opened 2023-07-06 17:03 UTC
### Source information and language

YOMIROLL 13.24

### Steps to reproduce

YOMIROLL extension doesn't load demon slayer and many animes on my device, It keeps loading and loading

### Expected behavior

Should load approximately in 5-10 sec

### Actual behavior

Doesn't even load

### Aniyomi version

beta

### Android version

android 12

### Acknowledgements

- [X] #1852
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment] 2023-07-06 17:57
Duplicate of #1720

**Closed by Samfun75** 2023-07-06 17:57 UTC
Labels: Bug
