### ISSUE TITLE
Sflix not working 

### ISSUE THREAD

**Issue by Prabhu-K4T** [aniyomiorg/aniyomi-extensions#3211] opened 2024-05-02 17:02 UTC
### Source information

Sflix 14.27 English 

### Source language

English

### Steps to reproduce

1. Tried opening the extension 
2. Not opening 
3. Checked the webveiw 
4. Still not opened
5. Checked the actual site and it works perfectly 

### Expected behavior

The extension should be opened or rather be updated 

### Actual behavior

The extension doesn't open

### Aniyomi version

Preview r7519

### Android version

Android 11

### Other details

I think the code should be updated 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-05-02 17:11
Duplicate of #2935

**Closed by Secozzi** 2024-05-02 17:11 UTC
Labels: Bug
