### ISSUE TITLE
Onedrive extension

### ISSUE THREAD

**Issue by kevin930321** [aniyomiorg/aniyomi-extensions#3315] opened 2024-06-07 16:03 UTC
### Source name

Onedrive

### Source language

All

### Describe your suggested feature

Connect to self owned Onedrive, play anime inside it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-06-07 16:15
Duplicate of #2511

**Closed by Secozzi** 2024-06-07 16:15 UTC
