### ISSUE TITLE
Aniwatch video loading issue

### ISSUE THREAD

**Issue by Imon24** [aniyomiorg/aniyomi-extensions#2594] opened 2023-12-01 13:27 UTC
### Source information

Aniwatch 13.36

### Source language

English

### Steps to reproduce

Sometimes works fine but sometimes video doesn't load. It has been happening for quite a while.

### Expected behavior

Videos should be loaded all the time.

### Actual behavior

Maximum times video doesn't load.

### Aniyomi version

Preview r6691

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-12-01 13:29
Duplicate of #2568

**Closed by Secozzi** 2023-12-01 13:29 UTC
Labels: Bug
