### ISSUE TITLE
Aniwave 14.66: Video list is empty.

### ISSUE THREAD

**Issue by ahykono** [aniyomiorg/aniyomi-extensions#2970] opened 2024-02-24 21:00 UTC
### Source information

Aniwave 14.66

### Source language

English

### Steps to reproduce

1. Open Aniyomi
2. Go to Browse Tab -> Anime Sources
3. Click Aniwave
4. Select any series 
5. Play an episode

### Expected behavior

Play the video

### Actual behavior

Closes the player & returns "Video list is empty."

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-02-24 21:03
Duplicate of #2967

**Closed by Secozzi** 2024-02-24 21:03 UTC
Labels: Bug
