### ISSUE TITLE
Add this website extension https://moviesmod.shop/

### ISSUE THREAD

**Issue by Tochage143** [aniyomiorg/aniyomi-extensions#2538] opened 2023-11-23 14:36 UTC
### Source name

Moviesmod

### Source link

https://moviesmod.shop/

### Source language

English, Hindi 

### Other details

The the website good download any movies,tv show and other things, also add settings for change the website domain name because this code change the domain in months .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-11-23 14:37
Duplicate of #1791

**Closed by Secozzi** 2023-11-23 14:37 UTC
Labels: Source request

**Comment by Tochage143** [comment] 2023-11-23 15:16
> Duplicate of #1791

I doesn't find moviemod extension on the app and also website 
![Uploading Screenshot_20231123-204502_Chrome.jpg…]()

**Comment by Secozzi** [comment] 2023-11-23 17:18
That's because there isn't any extension for it, but someone else has already requested it and there's no need for multiple requests for the same site, hence why it was marked as duplicate and closed.
