### ISSUE TITLE
FMovies URL Changed

### ISSUE THREAD

**Issue by Kylosor** [aniyomiorg/aniyomi-extensions#3317] opened 2024-06-07 23:59 UTC
### Source information

FMovies 14.24

### Source language

English

### Source new URL

https://fmovies24.to

### Other details

Upon visiting the original domain https://fmoviesz.to in WebView, text says that they've changed their domain to https://fmovies24.to and redirects to it after 5 seconds.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Appo777CXS** [comment] 2024-06-08 04:31
When they changed the domain, i was a little frustrated about it.

I hope this can be fixed soon. 👍

**Comment by Secozzi** [comment] 2024-06-08 09:30
Duplicate of #3287

**Closed by Secozzi** 2024-06-08 09:30 UTC
Labels: Bug, Domain changed
