### ISSUE TITLE
Anime Rulz

### ISSUE THREAD

**Issue by Coolboy067** [aniyomiorg/aniyomi-extensions#3150] opened 2024-04-09 13:04 UTC
### Source name

Anime Rulz

### Source link

https://animerulz.to

### Source language

Hindi

### Other details

We have two hindi sources anime world india and anime saga but it doesn't work fine so please add this new source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-04-09 13:12
Duplicate of #2750

**Closed by Secozzi** 2024-04-09 13:12 UTC
Labels: Source request
