### ISSUE TITLE
request extension(Animeiat)

### ISSUE THREAD

**Issue by Nour-Otaku** [aniyomiorg/aniyomi-extensions#1812] opened 2023-07-01 10:25 UTC
### Source name

Animeiat

### Source link

https://www.animeiat.tv/

### Language

Arabic

### Other details

A good site for watching anime and contains an average number of anime. 

Nsfw🔞=No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-01 10:58
Duplicate of #344

**Closed by Secozzi** 2023-07-01 10:58 UTC
Labels: Source request

**Comment by Nour-Otaku** [comment] 2023-07-01 11:47
@Secozzi Well, I will delete the message, but I want to know if request #344 is acceptable and is it being worked on?

**Comment by Nour-Otaku** [comment] 2023-07-01 11:55
Well I want to know is it my request or request #344 Acceptable, and I also
did not know that this request was repeated

**Comment by Nour-Otaku** [comment] 2023-07-01 15:40
@Unfortunately, I could not delete it. If I change the source request with another source, will the problem be solved because I know how to modify it?
