### ISSUE TITLE
Extension request

### ISSUE THREAD

**Issue by aadio7** [aniyomiorg/aniyomi-extensions#2354] opened 2023-10-11 17:15 UTC
### Source name

Vegamovies and dotmonster

### Source link

https://m.vegamovies.id/ and https://dotmovies.monster/

### Source language

English

### Other details

So this is vegamovies its a very good website .. and then there is dotmonster which is basically a different category(known as bollywood content in green bar) in big labelled at top of vegamovies website in which we click bollywood content which redirects from vegamovies to dotmonster ... so i request you to add vegamovies and dotmonster please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-10-11 17:17
Duplicate of #2180 
Also, please open up one issue per source

**Closed by Secozzi** 2023-10-11 17:17 UTC
Labels: Source request

**Comment by aadio7** [comment] 2023-10-12 02:23
> Duplicate of #2180 Also, please open up one issue per source

Idk there is already a req for vega..  so did you want to make vega?? Then also scrap from the "bollywood content" category which redirects to dotmovies.monsted
