### ISSUE TITLE
Aniwatch Isn't working 

### ISSUE THREAD

**Issue by Imon24** [aniyomiorg/aniyomi-extensions#1981] opened 2023-07-29 20:50 UTC
### Source information

Aniwatch 13.32

### Source language

English 

### Steps to reproduce

No episodes are loading or downloading.

### Expected behavior

Anime episodes should play and download.

### Actual behavior

No episodes are loading or downloading.

### Aniyomi version

r6151

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-29 21:23
Duplicate of #1931

**Closed by Secozzi** 2023-07-29 21:23 UTC
Labels: Bug
