### ISSUE TITLE
Deadtoonsindia

### ISSUE THREAD

**Issue by 1YuviKing1** [aniyomiorg/aniyomi-extensions#2257] opened 2023-09-24 08:18 UTC
### Source name

Deadtoons

### Source link

https://deadtoons.to

### Source language

Hindi

### Other details

+18/NSFW = no

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-09-24 08:28
Duplicate of #1856

**Closed by Secozzi** 2023-09-24 08:28 UTC
Labels: Source request

**Comment by 1YuviKing1** [comment] 2023-09-24 08:29
> Duplicate of #1856

Didn't know it already requested💀

**Comment by Claudemirovsky** [comment] 2023-09-24 08:29
Skill issue

**Comment by Secozzi** [comment] 2023-09-24 08:31
You acknowledged in the checklist that you searched through the issues and that you didn't open a duplicate issue. Please actually follow the checklist next time

**Comment by 1YuviKing1** [comment] 2023-09-24 08:32
> You acknowledged in the checklist that you searched through the issues and that you didn't open a duplicate issue. Please actually follow the checklist next time 

Need to scroll the list🗿

**Comment by Secozzi** [comment] 2023-09-24 08:33
GitHub has a search feature.
