### ISSUE TITLE
Rule34 is not working

### ISSUE THREAD

**Issue by Jeetchakraborty** [aniyomiorg/aniyomi-extensions#2243] opened 2023-09-23 03:38 UTC
### Source information

Rule34(13.6)

### Source language

English 

### Steps to reproduce

Rule34 is not working it shows loading error https error 403

### Expected behavior

Play the video 

### Actual behavior

Blank( loading error https error 403)

### Aniyomi version

Both stable and preview 

### Android version

Android 13

### Other details

I tried play in both aniyomi stable and preview but result is same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-09-23 07:51
Duplicate of #2206

**Closed by Secozzi** 2023-09-23 07:51 UTC
Labels: Bug
