### ISSUE TITLE
Filemoon host to Anizm

### ISSUE THREAD

**Issue by glaicodes** [aniyomiorg/aniyomi-extensions#3266] opened 2024-05-25 12:08 UTC
### Source name

Anizm

### Source language

Turkish

### Describe your suggested feature

Add Filemoon host to Anizm. 
https://filemoon.sx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by glaicodes** [comment] 2024-05-25 14:32
It's seems It's already in Anizm, but its broken. It gives "loading failed: http error 404 not found" error

**Comment by Secozzi** [comment] 2024-05-25 14:32
Duplicate of #3248

**Closed by Secozzi** 2024-05-25 14:32 UTC
Labels: Enhancement
