### ISSUE TITLE
Cannot find and play anime in GenoAnime extension 

### ISSUE THREAD

**Issue by rajinstar** [aniyomiorg/aniyomi-extensions#918] opened 2022-10-11 05:38 UTC
### Source information and language

GenoAnime 13.16 (English)

### Steps to reproduce

1) When I searched for anime in Global Search, I found my other extensions showed the desired results except for Genoanime.

2) When I click on Genoanime Extension, then every anime in the extension will only load but not show the anime thumbnail.

3) Videos aren't playing and showing that Invalid URL Host.

### Expected behavior

Anime should be available when I search.

### Actual behavior

But, when I search for any Anime, nothing is found.

### Aniyomi version

0.12.3.8-4515

### Android version

Android 11

### Other details

POCO M2 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-06-16 18:00
Duplicate of #737

**Closed by Secozzi** 2023-06-16 18:00 UTC
