### ISSUE TITLE
Animeindo Error 404

### ISSUE THREAD

**Issue by kitsu2** [aniyomiorg/aniyomi-extensions#3132] opened 2024-04-04 12:46 UTC
### Source information

Animeindo 14.12

### Source language

Indonesia 

### Steps to reproduce

1.open the extension it shows error 404
2.Normal Display in Webview 

### Expected behavior

It should show anime

### Actual behavior

Shows Error 404

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-04-04 13:36
Duplicate of #2725

**Closed by Secozzi** 2024-04-04 13:36 UTC
Labels: Bug
