### ISSUE TITLE
UNEXPECTED JSON ERROR  for ANIWAVE

### ISSUE THREAD

**Issue by krishnanunny001** [aniyomiorg/aniyomi-extensions#3109] opened 2024-03-28 14:04 UTC
### Source name

Aniwave

### Source language

English, Japanese

### Source link

https://aniwave.li/home

### Other details

Unexpected JSON token at offset 23: Expected string literal but 'null' literal was found at path: $.result
Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.
JSON input: {"status":403,"result":null,"message":"Request is invalid.","messages":["Request is invalid."]}

THIS IS THE ERROR POPPED WHEN TRIED OPENING **ANIWAVE ** EXTENSION ANIME.
![Screenshot_2024-03-28-19-33-26-976_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/102284873/4941a6e9-74b7-4644-9107-1d46e33d97f3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-28 14:37
Duplicate of #3100

**Closed by Secozzi** 2024-03-28 14:37 UTC
Labels: Source is down

**Comment by idzwan02** [comment] 2024-03-30 23:39
Help

**Comment by Diegopyl1209** [comment] 2024-03-31 00:08
no
