### ISSUE TITLE
English Anime YugenAnime

### ISSUE THREAD

**Issue by ponpon108** [aniyomiorg/aniyomi-extensions#2904] opened 2024-02-09 22:40 UTC
### Source name

YugenAnime

### Source link

https://yugenanime.tv/

### Source language

English

### Other details

![yugenanime](https://github.com/aniyomiorg/aniyomi-extensions/assets/159588044/b850664a-29b3-4bb2-9b49-62025c1e6ee8)
This Website similar Aniwave 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-02-10 14:50
Duplicate of #1112

**Closed by Secozzi** 2024-02-10 14:50 UTC
Labels: Source request
