### ISSUE TITLE
Aniwave fails to play anything 

### ISSUE THREAD

**Issue by J0n-b0** [aniyomiorg/aniyomi-extensions#3338] opened 2024-06-13 14:02 UTC
### Source information

Aniwave 14.69 (English)

### Source language

English 

### Steps to reproduce

1. Pick show
2. Play it
3. Observe error 

(Side note: descriptions and author info also fail to load)

### Expected behavior

It should play the show 

### Actual behavior

It doesn't 

### Aniyomi version

Preview r7567

### Android version

Android 14

### Other details

It seems the site has just added an additional security measure that includes a redirect. Might be the source of the issue 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-06-13 18:37
Duplicate of #3011

**Closed by Secozzi** 2024-06-13 18:37 UTC
Labels: Bug
