### ISSUE TITLE
SuperStream extension not working

### ISSUE THREAD

**Issue by vermaabhinav04** [aniyomiorg/aniyomi-extensions#3188] opened 2024-04-24 20:30 UTC
### Source information

"Super stream 14.11"

### Source language

"English"

### Steps to reproduce

1. When opening the extension.
2. An error is shown.
3. And pressing retry won't do anything.
![Screenshot_2024-04-25-01-53-04-803_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/156640602/cd3900d0-24e2-4276-8e32-8fd95709fa34)

### Expected behavior

All the content should be visible.

### Actual behavior

An error is shown.

### Aniyomi version

0.15.2.4

### Android version

Android 12

### Other details

Please fix this issue as soon as possible. I have to watch Movies and Web Series 🙏🏻

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-04-24 20:32
Duplicate of #3143

**Closed by Secozzi** 2024-04-24 20:32 UTC
Labels: Bug
