### ISSUE TITLE
JsonDecodingExeption

### ISSUE THREAD

**Issue by Zyo20** [aniyomiorg/aniyomi-extensions#2491] opened 2023-11-10 00:24 UTC
### Source information

Aniwave 13.57

### Source language

English

### Steps to reproduce

1. Open Aniyomi
2. Look for an anime from Aniwave source
3. Open the anime to load the episodes

### Expected behavior

What should happen is that episodes will load without any errors/issues.

### Actual behavior

Instead, the error 

"JsonDecodingException: Expected start of the object "{', but had 'EOF' instead at path: $

JSON input: .....Server at 9anime.eltik.net Port 80</address> </body></html>"

shows up and no episodes are loading

### Aniyomi version

Preview r6691

### Android version

Android 11

### Other details

![Screenshot_2023-11-10-08-20-28-20_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/24516479/906c73e2-6168-4aff-92c1-056bb234315f)
![Screenshot_2023-11-10-08-23-21-86_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/24516479/d0278147-9451-43b8-8206-c7b5221f36cc)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-11-10 07:22
Duplicate of #2483

**Closed by Secozzi** 2023-11-10 07:22 UTC
Labels: Bug
