### ISSUE TITLE
Streaming community: won't let me watch episodes 

### ISSUE THREAD

**Issue by abracadabra32** [aniyomiorg/aniyomi-extensions#2535] opened 2023-11-21 22:58 UTC
### Source information

StreamingCommunity 13.2 

### Source language

Italian

### Steps to reproduce

1. Choose a movie or series 
2. Click play on an episode 
3. The player opens and closes again 
4. You don't see the episode :(

### Expected behavior

I click on the episode, the episode starts and I can watch it 

### Actual behavior

When I click on an episode, the player closes and I can't see it

### Aniyomi version

r6691

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-11-21 23:00
Duplicate of #2477

**Closed by Secozzi** 2023-11-21 23:00 UTC
Labels: Bug
