### ISSUE TITLE
[Source Request] <anime: okanime - Shahiid anime * manga: teamx>

### ISSUE THREAD

**Issue by DzLahmer** [aniyomiorg/aniyomi-extensions#441] opened 2022-03-28 17:46 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application
  - In the multi-source spreadsheet: https://tachiyomi.org/extensions
  - By searching the GitHub repository for the extension and verify it does not appear in the code base
- I have searched the existing GitHub issues and this extension does **NOT** have an open request
- I will fill out the title and the information in this template

Note that the issue will be automatically closed if you do not fill out the title or requested information.

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

# anime Source website
## okanime
- Name: okanime
- Link: https://okanime.tv/
- Language(s): arabic
## Shahiid anime
- Name: Shahiid anime
- Link: https://shahiid-anime.net/
- Language(s): arabic

#  manga source website
## teamx
- Name: teamx
- Link: https://teamx.fun/
- Language(s): arabic

**Comment by DzLahmer** [comment] 2022-03-28 17:47
They are one of the best and More popular than the existed extension

**Comment by ahmedgamal17** [comment] 2022-03-28 17:52
For manga support go to tachiyomi extension repo

**Comment by DzLahmer** [comment] 2022-03-28 18:02
> 

I didn't find it in the app or in the site and in GitHub can you halo me !! Send me the link?

**Comment by ahmedgamal17** [comment] 2022-03-28 18:20
@DzLahmer  https://github.com/tachiyomiorg/tachiyomi-extensions

**Comment by DzLahmer** [comment] 2022-03-28 18:24
> @ahmedgamal17 
Thanks but I searched for teamX extension and didn't find it

**Comment by ahmedgamal17** [comment] 2022-03-28 18:26
@DzLahmer open the issue in tachiyomi for the manga source aniyomi is only for anime only for anime

**Comment by ahmedgamal17** [comment] 2022-03-28 18:27
And also you should close this issue as there Is already issue with these sources

**Comment by Samfun75** [comment] 2023-06-16 15:48
okanime is duplicate of #35 
manga request should go to tachiyomi github
Either rename issue with Shahiid anime and reopen or create a new source request

**Closed by Samfun75** 2023-06-16 15:48 UTC
