### ISSUE TITLE
9anime :- AniWave

### ISSUE THREAD

**Issue by KiritoX1** [aniyomiorg/aniyomi-extensions#2020] opened 2023-08-06 11:37 UTC
### Source information

9anime 13.46

### Source language

English

### Source new URL

Aniwave.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-08-06 21:28
Duplicate of #1999

**Closed by Secozzi** 2023-08-06 21:28 UTC
Labels: Bug, Domain changed
