### ISSUE TITLE
Episode not updating gogoanime 

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi-extensions#2996] opened 2024-03-04 10:38 UTC
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/245bbc40-fa9f-4bd1-a8f9-b4b58c1b4f2a)

### Expected behavior

Not episode are found is coming 

### Actual behavior

![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/842e26d7-0bd8-463d-9f46-45807dc93a6f)

### Aniyomi version

0.12.13.10

### Android version

Android 11

### Other details

Please 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-04 10:39
Duplicate of #2995

Please stop opening duplicate issues

**Closed by Secozzi** 2024-03-04 10:39 UTC
Labels: Bug

**Comment by avinave14102001** [comment] 2024-03-04 10:41
This are this problem is regional problem please solve this problem new episode new show not showing in GoGoAnime please solve this problem quickly and soon and possible
![Uploading Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8.jpg…]()

**Comment by avinave14102001** [comment] 2024-03-04 10:42
And why you are remove my problem and coming from go go Anime related you have not facing this problem to you go go look yourself this problem are coming or not coming the okay I am telling everyone please solve this problem if you have not coming problem I am also coming this problem that's why you are removing my problems
![Uploading Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8.jpg…]()

**Comment by Secozzi** [comment] 2024-03-04 10:43
I'm marking your issues as duplicate because there's already open issues/pull requests about the exact same issue. There isn't any need for multiple issues.
