### ISSUE TITLE
aniwatch.toURL change 

### ISSUE THREAD

**Issue by irukairu** [aniyomiorg/aniyomi-extensions#2828] opened 2024-01-26 08:07 UTC
### Source information

aniwatch 14.39 (english)

### Source language

english

### Steps to reproduce

Select aniwatch from the Browse tab.

### Expected behavior

A list of animations is displayed based on the source.

### Actual behavior

The message "No result found" will be displayed

### Aniyomi version

preview r7913

### Android version

Android14

### Other details

The URL for aniwatch appears to have changed to https://aniwatchtv.to/.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-01-26 10:23
Duplicate of #2690

**Closed by Secozzi** 2024-01-26 10:23 UTC
Labels: Bug
