### ISSUE TITLE
New Egy Dead URL

### ISSUE THREAD

**Issue by Bayuftj** [aniyomiorg/aniyomi-extensions#1897] opened 2023-07-13 15:24 UTC
### Source information and language

Egy Dead 13.2 (Arabic)

### Source new URL

https://a7.egydead.live/

### Other details

And fix the servers because they are not working, and make the download high quality, because most of the sites are solved with low quality

Thank you 😊💕

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-13 17:10
Duplicate of #1896

**Closed by Secozzi** 2023-07-13 17:10 UTC
Labels: Bug, Domain changed
