### ISSUE TITLE
AnimeSAGA 

### ISSUE THREAD

**Issue by bakaprince** [aniyomiorg/aniyomi-extensions#2797] opened 2024-01-20 10:03 UTC
### Source information

"AnimeSAGA 14.10(Hindi)

### Source language

Hindi

### Steps to reproduce

Open Any Anime 
The There Will Be No Episode List 
In Bottom It Shows "NullPointerException-null"

Solution:- There Is A Possibility That This Error is because Animesaga Has Moved To A New Domain Known As anplay.in

Kindly add a new extension anplay.in and remove the olde one,i.e, hi.animesaga

Please Fix the Issue 

### Expected behavior

Episode List Should Come 

### Actual behavior

A Single Video Titled Movie Comes With A Bottom Mssg of 
NullPointerException-null
![Screenshot_20240120-152848](https://github.com/aniyomiorg/aniyomi-extensions/assets/155534203/92a8db5a-10ac-4b8c-9862-09fee1735bd6)

### Aniyomi version

Previewr7473

### Android version

13

### Other details

If By Chance You Are Not Able To Fix This Issue Then Please Add another extension which provide hindi dubbed anime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-01-20 11:28
Duplicate of #2645

**Closed by Secozzi** 2024-01-20 11:28 UTC
Labels: Bug
