### ISSUE TITLE
Yomiroll: Couldn't find any video links

### ISSUE THREAD

**Issue by Bruh-Man14** [aniyomiorg/aniyomi-extensions#1721] opened 2023-06-13 08:06 UTC
### Source information and language

Yomiroll 13.24 (all)

### Steps to reproduce

Example in Naruto shippuden and demon slayer.
Begin playing an episode.

### Expected behavior

Anime should start playing

### Actual behavior

Instead of playing it exits the video and gives the prompt: "Couldn't find any video links".
![Screenshot_20230613-100450_Aniyomi](https://github.com/jmir1/aniyomi-extensions/assets/112637743/0a8cc9e4-fdcf-4c2e-accd-94e6d4f6af05)

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Other details

It only happens on certain anime I have no way to fix it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by yagereren** [comment] 2023-06-13 08:47
Those anime or ep of anime you are able to play on yomiroll are free on crunchy roll but those anime that have premium ep will not play . No idea when will it fixed

**Comment by Secozzi** [comment] 2023-06-16 12:49
Duplicate of #1720

**Closed by Secozzi** 2023-06-16 12:49 UTC
