### ISSUE TITLE
Fmovies url change 

### ISSUE THREAD

**Issue by GGGS9119** [aniyomiorg/aniyomi-extensions#3300] opened 2024-06-03 14:46 UTC
### Source information

Fmovies 

### Source language

English 

### Source new URL

Fmovies24.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-06-03 14:47
Duplicate of #3291

**Closed by Secozzi** 2024-06-03 14:47 UTC
Labels: Bug, Domain changed
