### ISSUE TITLE
720pizle

### ISSUE THREAD

**Issue by mriyangela** [aniyomiorg/aniyomi-extensions#2837] opened 2024-01-28 17:47 UTC
### Source name

720pizle

### Source link

https://720pizle.ai/

### Source language

Turkish 

### Other details

18+/Nsfw: No

A very good source for watching movies and TV series. I hope you will add this source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-01-28 17:48
Duplicate of #2378

**Closed by Secozzi** 2024-01-28 17:48 UTC
Labels: Source request
