### ISSUE TITLE
AnimeWorld India Source Not Working 

### ISSUE THREAD

**Issue by bakaprince** [aniyomiorg/aniyomi-extensions#2983] opened 2024-03-02 03:47 UTC
### Source information

AnimeWorld India 14.8

### Source language

Multi

### Steps to reproduce

Open Naruto Season 1 
Try to play Episode 1
The video is not playing 

### Expected behavior

The Episode Should Start Playing

### Actual behavior

A 0:07 sec clip always starts 

### Aniyomi version

r7509

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-02 08:15
Duplicate of #2956

**Comment by bakaprince** [comment] 2024-03-02 08:16
> Duplicate of #2956

But the issue is not fixed

**Closed by Secozzi** 2024-03-02 08:15 UTC
Labels: Bug

**Comment by Secozzi** [comment] 2024-03-02 08:17
Its still a duplicate
