### ISSUE TITLE
JsonDecodingExecption

### ISSUE THREAD

**Issue by Lolnod** [aniyomiorg/aniyomi-extensions#3144] opened 2024-04-07 10:26 UTC
### Source information

Aniwave 14.66 (English)

### Source language

English

### Steps to reproduce

1. First step (open any anime)
2. Issue here (it says "JsonDecodingException: Unexpected JSON token at offset 23: Expected string literal but 'null' literal was found at path: $.result Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values. JSON input: {"status":403,"result":null,"message":"Request is invalid.","messages":["Request is invalid."]}")
![Screenshot_2024-04-07-18-20-38-13_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/94206740/11a593d6-577c-411e-a596-af310c9f79e8)

### Expected behavior

I'm just gonna watch some anime.

### Actual behavior

Then this happened

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-04-07 10:27
Duplicate of #3100

**Closed by Secozzi** 2024-04-07 10:27 UTC
Labels: Bug
