### ISSUE TITLE
(Animension) Video list is empty.

### ISSUE THREAD

**Issue by nusbe-54** [aniyomiorg/aniyomi-extensions#2885] opened 2024-02-07 16:10 UTC
### Source information

Animension 14.20

### Source language

English

### Steps to reproduce

1. Choose any video to be played.
2. Click on the video.
3. The video player will load the video for a while.
4. The video player will close and went back to the app.
5. A message "Video list is empty" will be shown.

### Expected behavior

The video should play as usual.

### Actual behavior

A message "Video list is empty" appeared.
![Screenshot_20240207_154705_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/111195951/79f5e683-c4c9-4d72-ac4f-22ebd6b4840e)

### Aniyomi version

0.15.2.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-02-07 16:12
Duplicate of #2051

**Closed by Secozzi** 2024-02-07 16:12 UTC
Labels: Bug
