### ISSUE TITLE
Animeworld.so Servers to miss

### ISSUE THREAD

**Issue by Rufusnightly** [aniyomiorg/aniyomi-extensions#2473] opened 2023-11-06 03:00 UTC
### Source information

13.33

### Source language

Italiano

### Source new URL

Animeworld.so

### Other details

Please Add Servers video, thanks
![IMG_20231106_034648](https://github.com/aniyomiorg/aniyomi-extensions/assets/148594216/2264b0ea-fc37-437f-b578-4838671f716a)
![Screenshot_2023-11-06-03-55-33-33_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/148594216/dc94c761-6a8c-4d63-baa7-1a092e865eba)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-11-06 07:44
Duplicate of #1920

**Closed by Secozzi** 2023-11-06 07:44 UTC
Labels: Bug, Domain changed
