### ISSUE TITLE
9anime.to rebranded into AniWave.to

### ISSUE THREAD

**Issue by KiritoX1** [aniyomiorg/aniyomi-extensions#2019] opened 2023-08-06 11:24 UTC
### Source information

9anime 13.46

### Source language

English

### Steps to reproduce

1. Go to Browse
2. Open source 9anime
3. Not showing results at any available hosts. 

### Expected behavior

9anime should show animes. 

### Actual behavior

Not showing any result even after changing different hosts. 

### Aniyomi version

Preview r6453

### Android version

Android 11

### Other details

9anime.to Domain into AniWave.to
So please change it's Domain

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-08-06 21:28
Duplicate of #1999

**Closed by Secozzi** 2023-08-06 21:28 UTC
Labels: Bug
