### ISSUE TITLE
suggested a new source of Aniyomi: top cinema

### ISSUE THREAD

**Issue by 3bakri** [aniyomiorg/aniyomi-extensions#3121] opened 2024-03-30 16:11 UTC
### Source name

Top cinema 

### Source link

https://web.topcinema.cam 

### Source language

Arabic 

### Other details

This site contains many Anime and movies with Arabic subtitles
 
Has a lot of servers 
UpDown 
Ok
DoodStream
StreamWish
Streamtape 
Filelions 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-03-30 16:31
Why did you close #3115 and open this one?

**Comment by 3bakri** [comment] 2024-03-31 01:03
> Why did you close #3115 and open this one?

By mistake sorry 🙏

**Comment by Secozzi** [comment] 2024-03-31 08:26
Duplicate of #2470

**Closed by Secozzi** 2024-03-31 08:26 UTC
Labels: Source request
