### ISSUE TITLE
Source request anime content in India

### ISSUE THREAD

**Issue by ShankarKSH001** [aniyomiorg/aniyomi-extensions#2657] opened 2023-12-18 20:03 UTC
### Source name

Animedekho

### Source link

https://animedekho.com/

### Source language

Tamil, Hindi,Telugu, English

### Other details

It's a website that has largest anime content in Indian languages.
I hope you add these source thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-12-18 20:03
Duplicate of #2486

**Closed by Secozzi** 2023-12-18 20:03 UTC
Labels: Source request
