### ISSUE TITLE
[Source Request] <Youtube>

### ISSUE THREAD

**Issue by kaonkaon** [aniyomiorg/aniyomi-extensions#561] opened 2022-05-18 03:41 UTC
## Source website
- Name: Youtube
- Link: https://www.youtube.com/
- Language(s): En, Jp, Whatever

## Other details
Wouldnt it be funny if we can watch youtube videos and bookmark youtube channels on Aniyomi app using youtube api, whatever newpipe use, or those opensource youtube alternative api?

haha just kidding... unless?

**Comment by Samfun75** [comment] 2023-06-16 19:28
Duplicate of #320

**Closed by Samfun75** 2023-06-16 19:28 UTC
