### ISSUE TITLE
Tokuzilla

### ISSUE THREAD

**Issue by fo544** [aniyomiorg/aniyomi-extensions#2573] opened 2023-11-29 06:20 UTC
### Source information

Tokuzilla 

### Source language

English

### Steps to reproduce

1. Open any show e.g: Kamen Rider
2. video should play
3. list is empty

### Expected behavior

video should play

### Actual behavior

list is empty

### Aniyomi version

Preview r6691

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-11-29 08:57
Duplicate of #2510

**Closed by Secozzi** 2023-11-29 08:57 UTC
Labels: Bug
