### ISSUE TITLE
AnimeUnity extension is not working correctly.

### ISSUE THREAD

**Issue by Simsiano** [aniyomiorg/aniyomi-extensions#2693] opened 2024-01-02 14:29 UTC
### Source information

AnimeUnity (Italian)

### Source language

Italian

### Steps to reproduce

1. Download AnimeUnity extension.
2. Pick any anime.
3. Select any episode.
4. You will get an empty dialog pop-up at the bottom of the screen.

### Expected behavior

The episode should start playing.

### Actual behavior

An empty dialog pop-up box appears and the episode will not play.

### Aniyomi version

Preview r6691

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-01-02 14:30
Duplicate of #2534

**Closed by Secozzi** 2024-01-02 14:30 UTC
Labels: Bug
