### ISSUE TITLE
[Edit][Yomiroll] Yomiroll currently not working (No Connection / Connection Timeout)

### ISSUE THREAD

**Issue by PokiFLIX** [aniyomiorg/aniyomi-extensions#1940] opened 2023-07-21 11:35 UTC
### Source information

Yomiroll

### Source language

All

### Steps to reproduce

1. No Connection (Try to Search on Source)

### Expected behavior

Loading Anime

### Actual behavior

Connection Time out 

### Aniyomi version

Preview r6151

### Android version

Android 10

### Other details

Edit - App is not Crashing it was loading the Local Token Setting but could not Connect

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment] 2023-07-21 11:45
The crash happens when the proxy goes down, most phones handle this case correctly and show timeout. Chinese phones sometimes have weird behavior with Yomiroll's settings.

If it's just timeout just connect to a US vpn (to get all the catalogs) and turn on use local token. Please try this and close this issue if it works

**Comment by PokiFLIX** [comment] 2023-07-21 11:46
> The crash happens when the proxy goes down, most phones handle this case correctly and show timeout. Chinese phones sometimes have weird behavior with Yomiroll's settings.
> 
> If it's just timeout just connect to a US vpn (to get all the catalogs) and turn on use local token. Please try this and close this issue if it works

Yeah i checked it and it took just longer to load the Settings. i already edited the Post ^^

**Comment by Samfun75** [comment] 2023-07-21 11:48
> If it's just timeout just connect to a US vpn (to get all the catalogs) and turn on use local token. Please try this and close this issue if it works

Then try this when the proxy stops working.

**Comment by PokiFLIX** [comment] 2023-07-21 11:49
> > If it's just timeout just connect to a US vpn (to get all the catalogs) and turn on use local token. Please try this and close this issue if it works
> 
> Then try this when the proxy stops working.

VPN and Local Token Changed now it works ^^ Thx! do i need to disable it again? ^^

**Comment by Samfun75** [comment] 2023-07-21 11:50
No as the token will only last 5 mins you'll need the option and the VPN on to continue using the extension. Disable them when the proxy is back up.
Closing as the issue is resolved

**Closed by Samfun75** 2023-07-21 11:50 UTC
Labels: Bug
