### ISSUE TITLE
If any one gogoanime domain as be working or not facing same problem https://anitaku.to  ( host error) 

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi-extensions#2571] opened 2023-11-29 02:05 UTC
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

![Screenshot_2023-11-29-07-28-15-45_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/40632d60-1b4d-4fd4-bee2-245864588978)

### Expected behavior

If anyone as be  face same  problem 
Please tell how to solved this problem 😞🙏😭🙏
Because i am not understand after the changing gogoanime change domain name and https://anitaku.to domain name 
If anyone have idea how much time take this problem solved 

### Actual behavior

If anyone face how to solved this problem
If anyone tell me 
How time solved this problem 

If anyone have face same problem tell how time to take this problem solved 😭😭
Facing problem related gogoanime domain or website https://anitaku.to 

### Aniyomi version

0.12.13.10

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-11-29 08:59
Duplicate of #2570

**Closed by Secozzi** 2023-11-29 08:59 UTC
Labels: Bug
