### ISSUE TITLE
HentaiLa extension

### ISSUE THREAD

**Issue by Jipson2003** [aniyomiorg/aniyomi-extensions#1914] opened 2023-07-16 21:09 UTC
### Source information and language

Hentaila 13.12 Español

### Steps to reproduce

1. enter the hentaila extension
2. choose any hentai
3. open a chapter
4. wait for the chapter to come up

### Expected behavior

I would have to load the chapter

### Actual behavior

chapter does not load and stays loading

### Aniyomi version

preview r6151

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-07-24 10:09
Duplicate of #1786

**Closed by Secozzi** 2023-07-24 10:09 UTC
Labels: Bug
