### ISSUE TITLE
Wcostream is broking and can't watching anything 

### ISSUE THREAD

**Issue by Delmarcop52** [aniyomiorg/aniyomi-extensions#2424] opened 2023-10-26 13:29 UTC
### Source information

Wcostream 13.8

### Source language

English 

### Steps to reproduce

1.i trying to uninstall

### Expected behavior

The video is working 

### Actual behavior

Each time when I trying to watch it get close out 

### Aniyomi version

App version: 0.14.6-6678 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-10-27 09:51
Possible duplicate of #2059

**Closed by Secozzi** 2023-10-27 09:51 UTC
Labels: Bug
