### ISSUE TITLE
no extension available in the app

### ISSUE THREAD

**Issue by TwakiAsHellion** [aniyomiorg/aniyomi-extensions#3347] opened 2024-06-17 17:47 UTC
### Source information

Fmovies, allanime, allmovies, animeflix

### Source language

English

### Steps to reproduce

1. open the app
2. go to browse
3. go to anime extensions
4. there is no extensions other than google drive

### Expected behavior

extension list should have all the extension was available ago

### Actual behavior

the extension list is empty

### Aniyomi version

0.15.3.0

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-06-17 17:47
Duplicate of #3341

**Closed by Secozzi** 2024-06-17 17:47 UTC
Labels: Bug
